### ISSUE TITLE
Download links on the Puyo VS site failing because of mixed https -> http linking

### ISSUE THREAD

**Issue by ahiijny** [puyonexus/puyovs.com#1]
Hi, not sure if this is the right place to ask about this, but here goes!

When I try clicking on the links on this page https://puyovs.net/download.php , nothing happens.

I also noticed that in the browser console, this error appears:

![image](https://user-images.githubusercontent.com/5766317/133023986-10fc61b1-d95e-4369-a645-ab0f1791cf82.png)

I think the download links need to be changed from http -> https.

Also, I think the versions might also need to be updated? For Windows at least, it links to PuyoVS2_b28.zip, but when I asked about it in the PTG Discord, they gave me links to version PuyoVS2_b31.zip.

**Comment by jchv** [comment]
Sorry I never responded. The original issue here was fixed. The b28/b31 thing is... confusing, but I think we can safely update the links to b31 now.
